available_ids:
- asdsad0000
- asssmer
- autune
- b201xiaoli
- cdong121
- cfy002
- cheaterchow
- chencaihonga
- chengchi1007
- chenhao1213
- chenrunze11
- chuasiliu
- cq1234
- cshlhs
- cycyxcy
- dddd110
- denghaimeng
- dingziheng11
- djiangjiang
- du55148
- dusi605
- eastwangwei
- elong1202
- fakeid
- fanhuayang
- fzzy123
- geminiyy
- gloden613
- gorgeous0912
- guyuefangyuan6666
- houwen
- hsdfuieqg
- huoqiuxia
- hysz0821
- jacksisi
- jcy666
- jiangshuai0210
- jinzhanbo
- jiwei313
- jjjerry12138
- jokerking1
- jufuchao
- kanwenbin
- keyongkk
- kezzymik
- lemonlaila
- linyunlk243
- liucong12601
- luanjing
- ly1122
- maoshuwen0415
- miratowa1
- ohyeah00
- permanentlove
- phoenixcsw01
- pycjn666
- qcrqcrqcr
- qcx2333
- qinghui9527
- qqmail4092
- quepimao
- rmoope
- robinrainy
- roseqw
- rqmiraitowa
- rrrrmm
- rushly
- smartchaochao
- sollasi
- srmmmm
- sss45633
- ssss7777
- starysinger
- straghtwizard
- tangjiayuan1004
- tangjudge
- tangyujie123
- tianxianglii
- top1pcl
- ttzyty
- uamadeus
- wenyangtang
- wzywzy1227
- xiaoluoalice
- xpeng01
- xulijuan
- xulin5522
- xuwenhui123
- xwj66666
- xx03071425
- yangjiamin
- yangyangchengcheng
- yccwff
- ycy1n66
- yinmengmeng
- yuanhahah
- ywhicher
- yyyyjay
- zhangtingfengztf
- zhaotianchi
- zhikaiwang
- zhoujiahui0199
- zhoushuqing
- zhuangminghui
- zhuxinchen07
- zhuzichen123
- zjl001
- zongjiaxin
- zzr123123
exhausted_ids: []
sleep_time_hr: 0
poll_interval_minutes: 10
running_nodes:
- id: xulijuan
  left_time: 30.0
  notebooks:
  - kernel_id: xulijuan/n3r-default
    run_id: 0
    total_runs: 1
    start_time: '2026-02-24 16:00:23'
    resumed_from: null
    history_ids: []
finished_notebooks: []
error_notebooks: []
