defaults:
  - default

# strategy: ddp
strategy: ddp_find_unused_parameters_true

accelerator: gpu
devices: auto
num_nodes: 1
sync_batchnorm: true

use_distributed_sampler: false

check_val_every_n_epoch: 1
