defaults:
  - default

# strategy: ddp
strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  timeout:
    _target_: datetime.timedelta
    minutes: 30

accelerator: gpu
devices: auto
num_nodes: 1
sync_batchnorm: true

use_distributed_sampler: false
