_target_: fast3r.models.multiview_dust3r_module.MultiViewDUSt3RLitModule.load_for_inference

# pretrained: /lc/code/pretrained/fast3r
# pretrained: /lc/code/3D/a3R/logs/train/runs/2025-04-20_11-27-17/checkpoints/epoch_019.ckpt
# pretrained: /path/to/checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth
# resume_from_checkpoint: ${ckpt_path}

# log_detail: False
# eval_use_pts3d_from_local_head: true

# # compile model for faster training with pytorch 2.0
# compile: false


net:
  _target_: fast3r.models.fast3r.Fast3R.from_pretrained
  pretrained_model_name_or_path: /lc/code/pretrained/fast3r
  # ${model.pretrained}